version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5001:5000"
    env_file:
      - ./app/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dnb_db
    ports:
      - "5432:5432"
  # frontend:
  #   build:
  #     context: ./web-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./web-app:/usr/src/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - web

volumes:
  postgres_data:
